spring.application.name=devops-gateway
server.port = 8080

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.initialization-mode=always
spring.datasource.platform=postgres

spring.datasource.url=jdbc:postgresql://postgres:5432/devops_gateway_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

spring.jpa.open-in-view=true

#optimizacija za postgres upite
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

management.endpoints.web.exposure.include=health, info, metrics, prometheus
management.endpoint.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=devops-gateway

management.tracing.sampling.probability=1.0
management.tracing.enabled=true

management.zipkin.tracing.endpoint=http://tempo:9411/api/v2/spans

logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

loki.url=http://loki:3100/loki/api/v1/push

user.service.url=http://devops-user:8081
accommodation.service.url=http://devops-accommodation:8082
review.service.url=http://devops-review:8084
notification.service.url=devops-notifications:8083